- .github/templates/workflows/workflow.yaml
feat(#11 ) implemented using **gh-pages** and **mkdocs**.
> Feature #11/deploy mkdocs

- .vscode/extensions.json
- .vscode/settings.json
- src/app/layout.tsx
- src/app/page.tsx
- src/app/search/page.tsx
- src/components/ChartBar.tsx
- src/components/Header.tsx
Resolves #48 
As mudanças corrigem a identação do código, e configuram o lint e as extensões do editor de código.
- /.vscode/settings.json: configura o vscode para fazer as devidas correções de lint ao salvar o arquivo
- /.vscode/extensions.json: sugere as extensões recomendadas para o vscode em termos do projeto
- /src: identa o código da forma correta, removendo os antigos erros de lint
- "npx eslint ." executado com sucesso, sem erros de lint
Verificar a aplicação das modificações nos ambientes locais de cada integrante, configurando-os.
> Feature#48/configure eslint

- package-lock.json
- package.json
- src/app/search/page.tsx
- src/components/Filter.tsx
Resolves #49 
Criação e estilização dos filtros para os graficos da página Source .
- Criação de um componente Filter e estilização desse componente 
- Foram feitas alterações nos códigos de Filter.tsx e page.tsx, estilizando o componente e su posição na pagina
> Feature #49/implements filtes

- src/app/search/page.tsx
- src/components/Ranking.tsx
- tailwind.config.ts
Resolves #54 
Cria componente de ranking com opção de ordenação
- Run dev com sucesso
> Feature #54/ranking component

- docs/docs/index.md
- docs/docs/sprints/sprint-4.md
- docs/docs/sprints/sprint-5.md
- docs/mkdocs.yml
Resolves #56
Inclusão da documentação das sprints 4 e 5.
- run mkdocs serve com sucesso
> docs(#56): Updates sprint 4 documentation and includes sprint 5

- src/app/layout.tsx
- src/app/search/page.tsx
- src/components/Filter.tsx
- src/components/Ranking.tsx
- src/components/Subtopics.tsx
- src/components/Topics.tsx
- src/components/chart/GroupedBar.tsx
- tailwind.config.ts
Resolves #58 
- Implementa o gráfico horizontal e muda o modo de visualização.
- A aplicação foi compilada com sucesso.
> Feature #58/second topic search page

- docs/docs/sprints/sprint-6.md
- docs/docs/sprints/sprint-7.md
Resolves #Issue_Number
Provide a detailed description of the purpose of this pull request, explaining its relation to the referenced issue (if applicable).
- List all changes made, file by file
- Explain the key modifications made in each file
- Detail the tests conducted to validate these changes
- Include specific commands or instructions for reviewers to reproduce the tests
- Include before/after screenshots if your changes affect the user interface
Any extra information that reviewers need to know
> Feature #62/update sprints documentation

- src/app/search/page.tsx
Resolves #61
Inclusão do filtro 'Indicadores' no segundo gráfico e modificação dos filtros existentes no componente de Ranking.
- Inclui o filtro 'Indicadores' no segundo gráfico e 'Etapa de ensino' no componente do Ranking
- rodado em ambiente de desenvolvimento
> feature#61/update-search-page

- docs/docs/contributing.md
- docs/docs/environment.md
- docs/docs/sprints/sprint-7.md
- docs/docs/sprints/sprint-8.md
- docs/mkdocs.yml
Resolves #63
Atualiza o guia de contribuição com a configuração do ambiente de desenvolvimento. Atualiza a guia de sprints com a finalização da sprint 7 e abertura da sprint 8.
- run mkdocs serve in localhost with success
> Feature#63/update contribute

- src/app/search/page.tsx
- src/services/EnrollmentService.ts
- src/services/IndicatorsService.ts
- src/services/RankingService.ts
Resolves #68 
inclui arquivos com as classes de serviço que serão responsáveis pelas requisições, e também os effects que monitorarão as mudanças de estado nos filtros dos gráficos.
- logs em console
- run dev com sucesso
> Feature #68/initial service

- docs/docs/project/servicos.md
- docs/docs/sprints/sprint-8.md
- docs/docs/sprints/sprint-9.md
- docs/mkdocs.yml
Resolves #69
Inclusão da documentação sobre serviços da aplicação, além da documentação das sprints 8 e 9
-inclusao da pasta "servicos" em docs/docs/projects
- finalização da sprint 08 e início da sprint 09
> Feature#69/documentation

- package-lock.json
- package.json
- src/app/page.tsx
- src/components/Header.tsx
Resolves #73 
Adiçao de um menu sanduíche na página Home, bem como responsividade dessa página, alem de mudanças nos package.json e packag-lock.json.
- menu sanduiche 
-  responsividade da pagina Home 
- novas configurações
> Feature #73/responsive home

- src/components/Header.spec.tsx
Resolves #80 
Implementa testes unitarios do componente Header
- Todos os testes passaram
- Mais de 90% de cobertura de código
> tests#80: includes header unit tests

- .github/workflows/quality.yaml
- src/app/search/page.tsx
- src/components/FilterSearch.tsx
- src/components/Subtopics.tsx
- src/components/Topics.tsx
- vitest-setup.js
Resolves #82 
Implementa pipeline de qualidade: linter, testes e build
> ci#82: includes quality pipeline

- src/app/search/page.tsx
- src/components/FilterSearch.tsx
- src/components/Header.tsx
- src/components/Ranking.tsx
- src/components/Subtopics.tsx
- src/components/Topics.tsx
- src/components/chart/GroupedBar.tsx
- src/components/chart/StackedColumn.tsx
- src/data/filtersData.ts
- src/services/IndicatorsService.ts
Resolves #78 
arrumando bugs de responsividade e formatação e adicionando novo filtro no gráfico 2
- mudando as medidas dos gráficos
- adicionando formatações novas
- mudando a responsividade do ranking
- Testes manuais no navegador
> Fix#78/responsive rank

- src/app/search/page.spec.tsx
- src/app/search/page.tsx
- src/components/FilterSearch.tsx
- src/components/Ranking.tsx
- vitest.config.ts
Resolves #88 
Implementando testes da pagina de pesquisa
- Adiciona pasta de testes da search/page
- implementa id de testes no ranking e nos filtros
- Testes da library de renderização
> Feature #88/search tests

- src/components/FilterSearch.spec.tsx
Resolves #85 
Implementa os testes do componente de filtro
- Cria arquivo de testes para o filtro
- Testes de renderização e funcionalidade
> test(#85): implements filter tests

- src/components/Ranking.spec.tsx
Resolves #83 
IMplementando arquivo de testes do componente de ranking
- Cria arquivo de testes do componente de ranking
- Testes de renderizaçãona ordem solicitada ordem
> test(#83): implements ranking tests

- src/app/page.spec.tsx
- src/components/Subtopics.spec.tsx
- src/components/Subtopics.tsx
- src/components/Topics.spec.tsx
- src/components/Topics.tsx
Resolves #89 
Inclui testes da página Home
- Adição do arquivo de teste da pagina Home
- 
- Os testes incluem a renderização da pagina e se o botão "Descubra mais", quando clicado, vai para o arquivo certo, o teste possui 100% de cobertura do codigo
- Include before/after screenshots if your changes affect the user interface
> Feature #89/home test

- src/components/chart/GroupedBar.spec.tsx
- src/components/chart/GroupedBar.tsx
Resolves #86 
Inclui testes para o componente GroupedBarChart
adição do arquivo de teste e inclusao de um test-id no componente principal
-testa a renderização do componente
-possui cobertura de 100% do código
> Feature #86/grouped bar chart tests

- src/components/chart/StackedColumn.spec.tsx
- src/components/chart/StackedColumn.tsx
Resolves #87 
Implementando os testes do componente de gráfico
- Cria arquivo de testes e coloca uma id de testes no componente do gráfico
- Testes de renderização
> test(#87): implements stacked chart tests

- .github/workflows/workflow.yaml
- docs/docs/sprints/sprint-10.md
- docs/docs/sprints/sprint-11.md
- docs/docs/sprints/sprint-9.md
- docs/mkdocs.yml
Resolves #99 
Atualiza documentação da sprint 10 e 11
- List all changes made, file by file
- Explain the key modifications made in each file
Mkdcos executado em ambiente local
> Feature#99/documentation

- .env
- .gitignore
- src/app/search/page.tsx
- src/lib/axios.ts
- src/services/EnrollmentService.ts
- src/services/IndicatorsService.ts
- src/services/RankingService.ts
- src/types/Enrollment.ts
- src/types/Indicator.ts
- src/types/Ranking.ts
Resolves #104
Atualiza o código para estabelecer a conexão com o backend
- Modifica os dados na pagina de pesquisa
- Atualiza os services
- Implementa o axios
- Implementa os tipos de dados
> Feature#104/backend connection

- .github/workflows/deploy-docs.yaml
- .github/workflows/deploy-next.yaml
- .github/workflows/quality.yaml
Resolves #106 
Atualiza nome dos jobs das pipelines paronizando-as e a modifica o momento de run do deploy da documentação para push na main.
> chore#106: update jobs names

- package-lock.json
- package.json
Resolves #112
Inclui testes unitários e de linter antes de cada commit
> tests: includes pre commit testing lib

- src/app/search/page.spec.tsx
- src/app/search/page.tsx
- src/data/filtersData.ts
Resolves #116 
Arrumando bug nas divs de carregamento e ajustando dados estáticos para formato padrão.
- Testes de renderização e manuais.
> Fix #114/charts data

- package.json
- src/app/search/page.spec.tsx
- src/app/search/page.tsx
- src/components/FilterSearch.tsx
- src/components/Ranking.spec.tsx
- src/components/Ranking.tsx
- src/data/filtersData.ts
Resolves #118 
Altera o componente de ranking para atender as necessidades reais do projeto.
- Altera a lista recebida pelo ranking e seu tratamento
- Implementa lógica de manipulação do ranking para filtros e buscas por município e posição
- Altera estética do componente de select. 
- Altera funcionamento do componente de select: inclui propriedades para alterar o valor externamente, e para passar propriedades de tamanho específicas
- Altera página de pesquisa para atender aos novos elementos de busca do ranking.
- Testes unitários de renderização
- Testes locais
> Feature#118/usable ranking

- .github/workflows/deploy-next.yaml
- src/app/search/page.tsx
- src/components/FilterSearch.tsx
Resolves #119 
Arrumando a responsividade do filtros.
- Testes de responsividade
> Fix #119/responsive filters

- .github/workflows/preview.yaml
Resolves #124 
Inclui pipeline de deploy de preview
> feat: create preview deployment

- src/app/search/page.tsx
Resolves #127 
Arrumando bug no filtro de municípios do ranking.
- testes manuais.
> fix(#127): fixing filter wrap bug

- .env
- package-lock.json
- package.json
- src/app/layout.tsx
- src/app/search/page.tsx
- src/lib/axios.ts
- src/services/EnrollmentService.ts
- src/services/IndicatorsService.ts
- src/services/RankingService.ts
Resolves #128
Corrige ranking filters: remove order do service e passa a controlar localmente.
Trata os erros com o sonner, permitindo visualizações mais amigáveis
> Feature#128/toast sonner

- .github/workflows/quality.yaml
- README.md
- package-lock.json
- package.json
Resolves #129 
Adiciona codecov para cobertura de código.
> feat(#129): includes codecov in quality cli

- .github/workflows/quality.yaml
Resolves #129 
Atualiza a pipeline para rodar na main, gerando o coverage na branch correta
> chore(#129): includes push on main to quality pipeline

- .github/workflows/quality.yaml
Resolves #129 
Inclui codecov e push na main para rodar pipeline
> feat(#129): includes codecov and push on main

- .github/workflows/quality.yaml
- README.md
> codecov coverage

- next.config.mjs
- src/app/about/page.spec.tsx
- src/app/about/page.tsx
Resolves #115
adiciona a página sobre
> feat(#115): includes about page and tests

- src/app/search/page.spec.tsx
- src/app/search/page.tsx
- src/components/Ranking.tsx
- src/data/filtersData.ts
- src/services/IndicatorsService.ts
Resolves #144 
Alinhando frontend com backend, retirando filtro de rede e ajustando textos e testes.
> Feature #144/align frontend

- README.md
- docs/docs/contributing-backend.md
- docs/docs/project/arquitetura.md
- src/app/search/page.tsx
- src/components/chart/GroupedBar.tsx
Resolves #130
Atualiza ferramentas do backend na documetação e faz ajustes pontuais no next
> Feature#130/backend mkdocs

- package-lock.json
- package.json
- src/app/about/page.tsx
- src/app/search/page.tsx
Co-authored-by: rafgpereira <rafaelgomespereira123@gmail.com>
Resolves #147
Inclui os textos da página "Sobre"
> chore(#147): includes about texts and links and fixing ranking bug

- docs/docs/index.md
- docs/docs/project/arquitetura.md
- docs/docs/project/personas.md
- src/app/search/page.tsx
Resolves #150
Atualiza a documentação com motivação e fonte dos dados
> Feature#150/increase documentation
